/************************************************************************
 *    This file was generated by eTPU Graphical Configuration Tool        
 *                                                                        
 *    DO NOT EDIT !!! DO NOT EDIT !!! DO NOT EDIT !!! DO NOT EDIT !!!     
 *                                                                        
 *  DESCRIPTION:
 *  This file is generated together with the same name .c file.
 *  It contains function prototypes and useful defines.
 *
 *  Creation Date:  2018/11/15 13:35:00 
 *
 **************************************************************************/

/**************************************************************************
 * general macros
 **************************************************************************/
#define FS_ETPU_TCR1_PRESCALER(x)    (((x)-1) & 0xFF)
#define FS_ETPU_TCR2_PRESCALER(x)    ((((x)-1) & 0x3F)<<16)
#define FS_ETPU_TCR1_STAC_SRVSLOT(x) (((x) & 0xF)<<16)
#define FS_ETPU_TCR2_STAC_SRVSLOT(x) ((x) & 0xF)
#define FS_ETPU_CHANNEL_FUNCTION(x)  ((x) & 0x1F)
#define FS_ETPU_CHANNEL_PARAMS(x)    ((x) & 0x7F)
#define FS_ETPU_FUNCTION_MODE(x)     ((x) & 0x3)

#define FS_ETPU_ENTRY_TABLE_ADDR     (((FS_ETPU_ENTRY_TABLE)>>11) & 0x1F)

#define FS_ETPU_FUNCTION_MODE_00     FS_ETPU_FUNCTION_MODE(0)
#define FS_ETPU_FUNCTION_MODE_01     FS_ETPU_FUNCTION_MODE(1)
#define FS_ETPU_FUNCTION_MODE_10     FS_ETPU_FUNCTION_MODE(2)
#define FS_ETPU_FUNCTION_MODE_11     FS_ETPU_FUNCTION_MODE(3)

#define FS_ETPU_HSR_0                (0)
#define FS_ETPU_HSR_1                (1)
#define FS_ETPU_HSR_2                (2)
#define FS_ETPU_HSR_3                (3)
#define FS_ETPU_HSR_4                (4)
#define FS_ETPU_HSR_5                (5)
#define FS_ETPU_HSR_6                (6)
#define FS_ETPU_HSR_7                (7)

#define ETPU_ENGINE_A_CHANNEL(x)  (x)
#define ETPU_ENGINE_B_CHANNEL(x)  ((x)+64)
#define ETPU_CHAN_NOT_USED        (-1)

/**************************************************************************
 * define functions to channels
 **************************************************************************/
#define PWM0_CHANNEL	ETPU_ENGINE_A_CHANNEL(11)
#define PWM1_CHANNEL	ETPU_ENGINE_A_CHANNEL(12)
#define PWM2_CHANNEL	ETPU_ENGINE_A_CHANNEL(13)
#define PWM3_CHANNEL	ETPU_ENGINE_A_CHANNEL(14)
#define PWM4_CHANNEL	ETPU_ENGINE_A_CHANNEL(15)
#define PWM5_CHANNEL	ETPU_ENGINE_A_CHANNEL(16)
#define PWM6_CHANNEL	ETPU_ENGINE_A_CHANNEL(17)
#define PWM7_CHANNEL	ETPU_ENGINE_A_CHANNEL(18)

/**************************************************************************
 * Interrupt Enable, DMA Enable and Output Disable options
 * filled accodring to the user settings
 **************************************************************************/
#define ETPU_CIE_A    0x00000000
#define ETPU_DTRE_A   0x00000000
#define ETPU_ODIS_A   0x00000000
#define ETPU_OPOL_A   0x00000000
#define ETPU_CIE_B    0x00000000
#define ETPU_DTRE_B   0x00000000
#define ETPU_ODIS_B   0x00000000
#define ETPU_OPOL_B   0x00000000

/**************************************************************************
 * function prototypes
 **************************************************************************/
int32_t my_system_etpu_init ();
void    my_system_etpu_start();
void my_fs_etpu_pwm_update(uint8_t channel, uint32_t freq, uint16_t duty);

