/*
 * Interrupt.h
 *
 *  Created on: 2018Äê9ÔÂ6ÈÕ
 *      Author: helei
 */

#ifndef HAL_INTERRUPT_H_
#define HAL_INTERRUPT_H_

#include "typedefs.h"

#ifdef __INTERRPUT_GLOBALS__
#define __INTERRPUT_EXTERN__
#else
#define __INTERRPUT_EXTERN__  extern
#endif

__INTERRPUT_EXTERN__ void INT_CAN0_RX_ISR(void);
__INTERRPUT_EXTERN__ void INT_CAN1_RX_ISR(void);
__INTERRPUT_EXTERN__ void INT_CAN2_RX_ISR(void);
__INTERRPUT_EXTERN__ void INT_CAN3_RX_ISR(void);

__INTERRPUT_EXTERN__ void INT_ENET_TX_ISR(void);
__INTERRPUT_EXTERN__ void INT_ENET_RX_ISR(void);

__INTERRPUT_EXTERN__ void INT_RT_ISR(void);
__INTERRPUT_EXTERN__ void INT_PIT0_0_ISR(void);
__INTERRPUT_EXTERN__ void INT_PIT0_1_ISR(void);

__INTERRPUT_EXTERN__ void INT_eMIOS0_8_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_9_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_10_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_11_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_12_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_13_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_14_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_15_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_16_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_17_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_18_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_19_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_20_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_21_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS0_22_ISR(void);

__INTERRPUT_EXTERN__ void INT_eMIOS1_8_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_9_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_10_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_11_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_12_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_13_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_14_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_15_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_16_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_17_ISR(void);
//__INTERRPUT_EXTERN__ void INT_eMIOS1_18_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_19_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_20_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_21_ISR(void);
__INTERRPUT_EXTERN__ void INT_eMIOS1_22_ISR(void);



#endif /* HAL_INTERRUPT_H_ */
