/*
 * File: DHP_Cal_Data.h
 *
 * Code generated for Simulink model 'DHP_model'.
 *
 * Model version                  : 1.5367
 * Simulink Coder version         : 8.11 (R2016b) 25-Aug-2016
 * C/C++ source code generated on : Fri Mar 18 15:33:37 2022
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Freescale->32-bit PowerPC
 * Code generation objectives:
 *    1. Execution efficiency
 *    2. ROM efficiency
 *    3. RAM efficiency
 *    4. MISRA C:2012 guidelines
 * Validation result: Not run
 */

#ifndef RTW_HEADER_DHP_Cal_Data_h_
#define RTW_HEADER_DHP_Cal_Data_h_
#include "rtwtypes.h"
#include "zero_crossing_types.h"
#include "DHP_model_types.h"

/* Exported data define */

/* Definition for custom storage class: Define */
#define DHP_1000MSMSG_MISSINGTIME      5020U
#define DHP_100MSMSG_MISSINGTIME       1020U
#define DHP_10MSMSG_MISSINGTIME        150U
#define DHP_20MSMSG_MISSINGTIME        220U
#define DHP_300MSMSG_MISSINGTIME       3020U
#define DHP_500MSMSG_MISSINGTIME       5020U
#define DHP_DIAGENABLE_VOLTDOWN        90U
#define DHP_DIAGENABLE_VOLTUP          160U
#define DHP_HW_VCU20                   32U
#define DHP_MISSINGECUTIME_MS          2020U
#define DHP_PWRLIMITLAMP_PCT           100U
#define DHP_SPDLIMITLAMP_KPH           60U
#define ENUM_GEARD1_YK19               12U
#define ENUM_GEARD2_YK19               9U
#define ENUM_GEARD3_YK19               5U
#define ENUM_GEARD4_YK19               6U
#define ENUM_GEARD5_YK19               3U
#define ENUM_GEARN_YK19                15U
#define ENUM_GEARR_YK19                10U
#define KDHP_ABS232MISSINGALLOWRECOVERY_FLG 1
#define KDHP_ABS232MISSINGFAULTLEVEL_ENUM 1U
#define KDHP_ABS232MISSINGHANDLERESPONSEBITS 0U
#define KDHP_ABS232MISSINGPOWERLIMIT_PCT 100U
#define KDHP_ABS232MISSINGSPDLIMIT     200U
#define KDHP_ABSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_ABSLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_ABSLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_ABSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_ABSLOSSCANNETSPDLIMIT     200U
#define KDHP_ABSSPDINVALIDALLOWRECOVERY_FLG 1
#define KDHP_ABSSPDINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_ABSSPDINVALIDHANDLERESPONSEBITS 0U
#define KDHP_ABSSPDINVALIDPOWERLIMIT_PCT 100U
#define KDHP_ABSSPDINVALIDSPDLIMIT     200U
#define KDHP_ABSWORKERRALLOWRECOVERY_FLG 1
#define KDHP_ABSWORKERRFAULTLEVEL_ENUM 2U
#define KDHP_ABSWORKERRHANDLERESPONSEBITS 0U
#define KDHP_ABSWORKERRPOWERLIMIT_PCT  100U
#define KDHP_ABSWORKERRSPDLIMIT        200U
#define KDHP_ACCELPDLRATALLOWRECOVERY_FLG 1
#define KDHP_ACCELPDLRATCLEARTIME_MS   400U
#define KDHP_ACCELPDLRATCONFIRMTIME_MS 400U
#define KDHP_ACCELPDLRATDEATHALLOWRECOVERY_FLG 1
#define KDHP_ACCELPDLRATDEATHCLEARTIME_MS 400U
#define KDHP_ACCELPDLRATDEATHCONFIRMTIME_MS 400U
#define KDHP_ACCELPDLRATDEATHFAULTLEVEL_ENUM 2U
#define KDHP_ACCELPDLRATDEATHHANDLERESPONSEBITS 0U
#define KDHP_ACCELPDLRATDEATHPOWERLIMIT_PCT 100U
#define KDHP_ACCELPDLRATDEATHSPDLIMIT  8U
#define KDHP_ACCELPDLRATFAULTLEVEL_ENUM 2U
#define KDHP_ACCELPDLRATHANDLERESPONSEBITS 0U
#define KDHP_ACCELPDLRATPOWERLIMIT_PCT 100U
#define KDHP_ACCELPDLRATSPDLIMIT       40U
#define KDHP_ACCHWSIGNALABNORMALALLOWRECOVERY_FLG 1
#define KDHP_ACCHWSIGNALABNORMALCLEARTIME_MS 1U
#define KDHP_ACCHWSIGNALABNORMALCONFIRMTIME_MS 1U
#define KDHP_ACCHWSIGNALABNORMALFAULTLEVEL_ENUM 1U
#define KDHP_ACCHWSIGNALABNORMALHANDLERESPONSEBITS 0U
#define KDHP_ACCHWSIGNALABNORMALPOWERLIMIT_PCT 100U
#define KDHP_ACCHWSIGNALABNORMALSPDLIMIT 200U
#define KDHP_ACCPDLHVOLTHIGHALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLHVOLTHIGHCLEARTIME_MS 400U
#define KDHP_ACCPDLHVOLTHIGHCONFIRMTIME_MS 400U
#define KDHP_ACCPDLHVOLTHIGHFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLHVOLTHIGHHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLHVOLTHIGHPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLHVOLTHIGHSPDLIMIT   200U
#define KDHP_ACCPDLHVOLTLOWALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLHVOLTLOWCLEARTIME_MS 400U
#define KDHP_ACCPDLHVOLTLOWCONFIRMTIME_MS 400U
#define KDHP_ACCPDLHVOLTLOWFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLHVOLTLOWHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLHVOLTLOWPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLHVOLTLOWSPDLIMIT    200U
#define KDHP_ACCPDLLHVOLTDEATHALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLLHVOLTDEATHCLEARTIME_MS 400U
#define KDHP_ACCPDLLHVOLTDEATHCONFIRMTIME_MS 400U
#define KDHP_ACCPDLLHVOLTDEATHFAULTLEVEL_ENUM 2U
#define KDHP_ACCPDLLHVOLTDEATHHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLLHVOLTDEATHPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLLHVOLTDEATHSPDLIMIT 8U
#define KDHP_ACCPDLLVOLTHIGHALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLLVOLTHIGHCLEARTIME_MS 400U
#define KDHP_ACCPDLLVOLTHIGHCONFIRMTIME_MS 400U
#define KDHP_ACCPDLLVOLTHIGHFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLLVOLTHIGHHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLLVOLTHIGHPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLLVOLTHIGHSPDLIMIT   200U
#define KDHP_ACCPDLLVOLTLOWALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLLVOLTLOWCLEARTIME_MS 400U
#define KDHP_ACCPDLLVOLTLOWCONFIRMTIME_MS 400U
#define KDHP_ACCPDLLVOLTLOWFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLLVOLTLOWHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLLVOLTLOWPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLLVOLTLOWSPDLIMIT    200U
#define KDHP_ACCPDLSENREFVOLTHIGHALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLSENREFVOLTHIGHCLEARTIME_MS 400U
#define KDHP_ACCPDLSENREFVOLTHIGHCONFIRMTIME_MS 400U
#define KDHP_ACCPDLSENREFVOLTHIGHFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLSENREFVOLTHIGHHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLSENREFVOLTHIGHPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLSENREFVOLTHIGHSPDLIMIT 200U
#define KDHP_ACCPDLSENREFVOLTLOWALLOWRECOVERY_FLG 1
#define KDHP_ACCPDLSENREFVOLTLOWCLEARTIME_MS 400U
#define KDHP_ACCPDLSENREFVOLTLOWCONFIRMTIME_MS 400U
#define KDHP_ACCPDLSENREFVOLTLOWFAULTLEVEL_ENUM 1U
#define KDHP_ACCPDLSENREFVOLTLOWHANDLERESPONSEBITS 0U
#define KDHP_ACCPDLSENREFVOLTLOWPOWERLIMIT_PCT 100U
#define KDHP_ACCPDLSENREFVOLTLOWSPDLIMIT 200U
#define KDHP_APPDATA12DFLASHINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA12DFLASHINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA12DFLASHINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA12DFLASHINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA12DFLASHINVALIDSPDLIMIT 200U
#define KDHP_APPDATA12EEPROMINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA12EEPROMINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA12EEPROMINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA12EEPROMINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA12EEPROMINVALIDSPDLIMIT 200U
#define KDHP_APPDATA3DFLASHINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA3DFLASHINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA3DFLASHINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA3DFLASHINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA3DFLASHINVALIDSPDLIMIT 200U
#define KDHP_APPDATA3EEPROMINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA3EEPROMINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA3EEPROMINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA3EEPROMINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA3EEPROMINVALIDSPDLIMIT 200U
#define KDHP_APPDATA4DFLASHINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA4DFLASHINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA4DFLASHINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA4DFLASHINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA4DFLASHINVALIDSPDLIMIT 200U
#define KDHP_APPDATA4EEPROMINVALIDALLOWRECOVERY_FLG 1
#define KDHP_APPDATA4EEPROMINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATA4EEPROMINVALIDHANDLERESPONSEBITS 0U
#define KDHP_APPDATA4EEPROMINVALIDPOWERLIMIT_PCT 100U
#define KDHP_APPDATA4EEPROMINVALIDSPDLIMIT 200U
#define KDHP_APPDATACHECKFAILEDALLOWRECOVERY_FLG 1
#define KDHP_APPDATACHECKFAILEDFAULTLEVEL_ENUM 1U
#define KDHP_APPDATACHECKFAILEDHANDLERESPONSEBITS 0U
#define KDHP_APPDATACHECKFAILEDPOWERLIMIT_PCT 100U
#define KDHP_APPDATACHECKFAILEDSPDLIMIT 200U
#define KDHP_AUXBATTVOLTHIGHFLTALLOWRECOVERY_FLG 1
#define KDHP_AUXBATTVOLTHIGHFLTCLEARTIME_MS 20000U
#define KDHP_AUXBATTVOLTHIGHFLTCONFIRMTIME_MS 10000U
#define KDHP_AUXBATTVOLTHIGHFLTFAULTLEVEL_ENUM 2U
#define KDHP_AUXBATTVOLTHIGHFLTHANDLERESPONSEBITS 0U
#define KDHP_AUXBATTVOLTHIGHFLTPOWERLIMIT_PCT 20U
#define KDHP_AUXBATTVOLTHIGHFLTSPDLIMIT 8U
#define KDHP_AUXBATTVOLTHIGHWARNALLOWRECOVERY_FLG 1
#define KDHP_AUXBATTVOLTHIGHWARNCLEARTIME_MS 2000U
#define KDHP_AUXBATTVOLTHIGHWARNCONFIRMTIME_MS 2000U
#define KDHP_AUXBATTVOLTHIGHWARNFAULTLEVEL_ENUM 2U
#define KDHP_AUXBATTVOLTHIGHWARNHANDLERESPONSEBITS 0U
#define KDHP_AUXBATTVOLTHIGHWARNPOWERLIMIT_PCT 50U
#define KDHP_AUXBATTVOLTHIGHWARNSPDLIMIT 80U
#define KDHP_AUXBATTVOLTLOWFLTALLOWRECOVERY_FLG 1
#define KDHP_AUXBATTVOLTLOWFLTCLEARTIME_MS 20000U
#define KDHP_AUXBATTVOLTLOWFLTCONFIRMTIME_MS 10000U
#define KDHP_AUXBATTVOLTLOWFLTFAULTLEVEL_ENUM 2U
#define KDHP_AUXBATTVOLTLOWFLTHANDLERESPONSEBITS 0U
#define KDHP_AUXBATTVOLTLOWFLTPOWERLIMIT_PCT 20U
#define KDHP_AUXBATTVOLTLOWFLTSPDLIMIT 8U
#define KDHP_AUXBATTVOLTLOWWARNALLOWRECOVERY_FLG 1
#define KDHP_AUXBATTVOLTLOWWARNCLEARTIME_MS 2000U
#define KDHP_AUXBATTVOLTLOWWARNCONFIRMTIME_MS 2000U
#define KDHP_AUXBATTVOLTLOWWARNFAULTLEVEL_ENUM 2U
#define KDHP_AUXBATTVOLTLOWWARNHANDLERESPONSEBITS 0U
#define KDHP_AUXBATTVOLTLOWWARNPOWERLIMIT_PCT 50U
#define KDHP_AUXBATTVOLTLOWWARNSPDLIMIT 80U
#define KDHP_BATTENERGYTOOLOWALLOWRECOVERY_FLG 0
#define KDHP_BATTENERGYTOOLOWFAULTLEVEL_ENUM 3U
#define KDHP_BATTENERGYTOOLOWHANDLERESPONSEBITS 8191U
#define KDHP_BATTENERGYTOOLOWPOWERLIMIT_PCT 0U
#define KDHP_BATTENERGYTOOLOWSPDLIMIT  0U
#define KDHP_BMS113MISSINGALLOWRECOVERY_FLG 1
#define KDHP_BMS113MISSINGFAULTLEVEL_ENUM 2U
#define KDHP_BMS113MISSINGHANDLERESPONSEBITS 0U
#define KDHP_BMS113MISSINGPOWERLIMIT_PCT 100U
#define KDHP_BMS113MISSINGSPDLIMIT     200U
#define KDHP_BMS303MISSINGALLOWRECOVERY_FLG 1
#define KDHP_BMS303MISSINGFAULTLEVEL_ENUM 2U
#define KDHP_BMS303MISSINGHANDLERESPONSEBITS 0U
#define KDHP_BMS303MISSINGPOWERLIMIT_PCT 100U
#define KDHP_BMS303MISSINGSPDLIMIT     200U
#define KDHP_BMSBATTOVERTALLOWRECOVERY_FLG 0
#define KDHP_BMSBATTOVERTCLEARTIME_MS  400U
#define KDHP_BMSBATTOVERTCONFIRMTIME_MS 3500U
#define KDHP_BMSBATTOVERTFAULTLEVEL_ENUM 3U
#define KDHP_BMSBATTOVERTHANDLERESPONSEBITS 8191U
#define KDHP_BMSBATTOVERTPOWERLIMIT_PCT 0U
#define KDHP_BMSBATTOVERTSPDLIMIT      0U
#define KDHP_BMSCELLOVERUALLOWRECOVERY_FLG 0
#define KDHP_BMSCELLOVERUCLEARTIME_MS  400U
#define KDHP_BMSCELLOVERUCONFIRMTIME_MS 2500U
#define KDHP_BMSCELLOVERUFAULTLEVEL_ENUM 3U
#define KDHP_BMSCELLOVERUHANDLERESPONSEBITS 8191U
#define KDHP_BMSCELLOVERUPOWERLIMIT_PCT 0U
#define KDHP_BMSCELLOVERUSPDLIMIT      0U
#define KDHP_BMSCELLUNDERUALLOWRECOVERY_FLG 0
#define KDHP_BMSCELLUNDERUCLEARTIME_MS 400U
#define KDHP_BMSCELLUNDERUCONFIRMTIME_MS 2500U
#define KDHP_BMSCELLUNDERUFAULTLEVEL_ENUM 3U
#define KDHP_BMSCELLUNDERUHANDLERESPONSEBITS 8191U
#define KDHP_BMSCELLUNDERUPOWERLIMIT_PCT 0U
#define KDHP_BMSCELLUNDERUSPDLIMIT     0U
#define KDHP_BMSDISCHRGPWRABNORMALALLOWRECOVERY_FLG 1
#define KDHP_BMSDISCHRGPWRABNORMALFAULTLEVEL_ENUM 1U
#define KDHP_BMSDISCHRGPWRABNORMALHANDLERESPONSEBITS 0U
#define KDHP_BMSDISCHRGPWRABNORMALPOWERLIMIT_PCT 100U
#define KDHP_BMSDISCHRGPWRABNORMALSPDLIMIT 200U
#define KDHP_BMSFLT2ALLOWRECOVERY_FLG  1
#define KDHP_BMSFLT2FAULTLEVEL_ENUM    2U
#define KDHP_BMSFLT2HANDLERESPONSEBITS 0U
#define KDHP_BMSFLT2POWERLIMIT_PCT     100U
#define KDHP_BMSFLT2SPDLIMIT           200U
#define KDHP_BMSFLT3ALLOWRECOVERY_FLG  0
#define KDHP_BMSFLT3FAULTLEVEL_ENUM    3U
#define KDHP_BMSFLT3HANDLERESPONSEBITS 8191U
#define KDHP_BMSFLT3POWERLIMIT_PCT     0U
#define KDHP_BMSFLT3SPDLIMIT           0U
#define KDHP_BMSFLT4ALLOWRECOVERY_FLG  0
#define KDHP_BMSFLT4FAULTLEVEL_ENUM    4U
#define KDHP_BMSFLT4HANDLERESPONSEBITS 16383U
#define KDHP_BMSFLT4POWERLIMIT_PCT     0U
#define KDHP_BMSFLT4SPDLIMIT           0U
#define KDHP_BMSFLTUNMATCHALLOWRECOVERY_FLG 1
#define KDHP_BMSFLTUNMATCHFAULTLEVEL_ENUM 1U
#define KDHP_BMSFLTUNMATCHHANDLERESPONSEBITS 0U
#define KDHP_BMSFLTUNMATCHPOWERLIMIT_PCT 100U
#define KDHP_BMSFLTUNMATCHSPDLIMIT     200U
#define KDHP_BMSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_BMSLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_BMSLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_BMSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_BMSLOSSCANNETSPDLIMIT     200U
#define KDHP_BMSMISSINGALLOWRECOVERY_FLG 0
#define KDHP_BMSMISSINGFAULTLEVEL_ENUM 2U
#define KDHP_BMSMISSINGHANDLERESPONSEBITS 1280U
#define KDHP_BMSMISSINGPOWERLIMIT_PCT  20U
#define KDHP_BMSMISSINGSPDLIMIT        8U
#define KDHP_BMSMODEERRALLOWRECOVERY_FLG 0
#define KDHP_BMSMODEERRFAULTLEVEL_ENUM 3U
#define KDHP_BMSMODEERRHANDLERESPONSEBITS 8191U
#define KDHP_BMSMODEERRPOWERLIMIT_PCT  0U
#define KDHP_BMSMODEERRSPDLIMIT        0U
#define KDHP_BMSOVERUALLOWRECOVERY_FLG 0
#define KDHP_BMSOVERUCLEARTIME_MS      400U
#define KDHP_BMSOVERUCONFIRMTIME_MS    4000U
#define KDHP_BMSOVERUFAULTLEVEL_ENUM   3U
#define KDHP_BMSOVERUHANDLERESPONSEBITS 8191U
#define KDHP_BMSOVERUPOWERLIMIT_PCT    0U
#define KDHP_BMSOVERUSPDLIMIT          0U
#define KDHP_BMSUNDERUALLOWRECOVERY_FLG 0
#define KDHP_BMSUNDERUCLEARTIME_MS     400U
#define KDHP_BMSUNDERUCONFIRMTIME_MS   4000U
#define KDHP_BMSUNDERUFAULTLEVEL_ENUM  3U
#define KDHP_BMSUNDERUHANDLERESPONSEBITS 8191U
#define KDHP_BMSUNDERUPOWERLIMIT_PCT   0U
#define KDHP_BMSUNDERUSPDLIMIT         0U
#define KDHP_BRKDSCHECK0ALLOWRECOVERY_FLG 1
#define KDHP_BRKDSCHECK0CLEARTIME_MS   400U
#define KDHP_BRKDSCHECK0CONFIRMTIME_MS 400U
#define KDHP_BRKDSCHECK0FAULTLEVEL_ENUM 2U
#define KDHP_BRKDSCHECK0HANDLERESPONSEBITS 0U
#define KDHP_BRKDSCHECK0POWERLIMIT_PCT 100U
#define KDHP_BRKDSCHECK0SPDLIMIT       200U
#define KDHP_BRKDSCHECK1ALLOWRECOVERY_FLG 1
#define KDHP_BRKDSCHECK1CLEARTIME_MS   1U
#define KDHP_BRKDSCHECK1CONFIRMTIME_MS 60000U
#define KDHP_BRKDSCHECK1FAULTLEVEL_ENUM 1U
#define KDHP_BRKDSCHECK1HANDLERESPONSEBITS 0U
#define KDHP_BRKDSCHECK1POWERLIMIT_PCT 100U
#define KDHP_BRKDSCHECK1SPDLIMIT       200U
#define KDHP_CALDATACHECKFAILEDALLOWRECOVERY_FLG 0
#define KDHP_CALDATACHECKFAILEDFAULTLEVEL_ENUM 3U
#define KDHP_CALDATACHECKFAILEDHANDLERESPONSEBITS 8191U
#define KDHP_CALDATACHECKFAILEDPOWERLIMIT_PCT 0U
#define KDHP_CALDATACHECKFAILEDSPDLIMIT 0U
#define KDHP_CHRGFAULTALLOWRECOVERY_FLG 1
#define KDHP_CHRGFAULTFAULTLEVEL_ENUM  1U
#define KDHP_CHRGFAULTHANDLERESPONSEBITS 0U
#define KDHP_CHRGFAULTPOWERLIMIT_PCT   100U
#define KDHP_CHRGFAULTSPDLIMIT         200U
#define KDHP_CHRGLOCKCHECKTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_CHRGLOCKCHECKTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_CHRGLOCKCHECKTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_CHRGLOCKCHECKTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_CHRGLOCKCHECKTIMEOUTSPDLIMIT 200U
#define KDHP_CHRGMODEABNORMALALLOWRECOVERY_FLG 1
#define KDHP_CHRGMODEABNORMALFAULTLEVEL_ENUM 1U
#define KDHP_CHRGMODEABNORMALHANDLERESPONSEBITS 0U
#define KDHP_CHRGMODEABNORMALPOWERLIMIT_PCT 100U
#define KDHP_CHRGMODEABNORMALSPDLIMIT  200U
#define KDHP_CHRGMODEINVALIDALLOWRECOVERY_FLG 1
#define KDHP_CHRGMODEINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_CHRGMODEINVALIDHANDLERESPONSEBITS 0U
#define KDHP_CHRGMODEINVALIDPOWERLIMIT_PCT 100U
#define KDHP_CHRGMODEINVALIDSPDLIMIT   200U
#define KDHP_CHRGOBCSLEEPTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_CHRGOBCSLEEPTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_CHRGOBCSLEEPTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_CHRGOBCSLEEPTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_CHRGOBCSLEEPTIMEOUTSPDLIMIT 200U
#define KDHP_CHRGSTOPABNORMALALLOWRECOVERY_FLG 1
#define KDHP_CHRGSTOPABNORMALFAULTLEVEL_ENUM 1U
#define KDHP_CHRGSTOPABNORMALHANDLERESPONSEBITS 0U
#define KDHP_CHRGSTOPABNORMALPOWERLIMIT_PCT 100U
#define KDHP_CHRGSTOPABNORMALSPDLIMIT  200U
#define KDHP_CHRGSTOPLOCKERRALLOWRECOVERY_FLG 1
#define KDHP_CHRGSTOPLOCKERRFAULTLEVEL_ENUM 1U
#define KDHP_CHRGSTOPLOCKERRHANDLERESPONSEBITS 0U
#define KDHP_CHRGSTOPLOCKERRPOWERLIMIT_PCT 100U
#define KDHP_CHRGSTOPLOCKERRSPDLIMIT   200U
#define KDHP_CHRGSTOPMODEINVALIDALLOWRECOVERY_FLG 1
#define KDHP_CHRGSTOPMODEINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_CHRGSTOPMODEINVALIDHANDLERESPONSEBITS 0U
#define KDHP_CHRGSTOPMODEINVALIDPOWERLIMIT_PCT 100U
#define KDHP_CHRGSTOPMODEINVALIDSPDLIMIT 200U
#define KDHP_CHRGSTOPOPERTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_CHRGSTOPOPERTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_CHRGSTOPOPERTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_CHRGSTOPOPERTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_CHRGSTOPOPERTIMEOUTSPDLIMIT 200U
#define KDHP_COOLSYSERRALLOWRECOVERY_FLG 1
#define KDHP_COOLSYSERRCLEARTIME_MS    20000U
#define KDHP_COOLSYSERRCONFIRMTIME_MS  10000U
#define KDHP_COOLSYSERRFAULTLEVEL_ENUM 2U
#define KDHP_COOLSYSERRHANDLERESPONSEBITS 0U
#define KDHP_COOLSYSERRPOWERLIMIT_PCT  100U
#define KDHP_COOLSYSERRSPDLIMIT        200U
#define KDHP_CRUISEKEYJAMFLTALLOWRECOVERY_FLG 1
#define KDHP_CRUISEKEYJAMFLTFAULTLEVEL_ENUM 1U
#define KDHP_CRUISEKEYJAMFLTHANDLERESPONSEBITS 1U
#define KDHP_CRUISEKEYJAMFLTPOWERLIMIT_PCT 100U
#define KDHP_CRUISEKEYJAMFLTSPDLIMIT   200U
#define KDHP_CRUISEKEYOPENFLTALLOWRECOVERY_FLG 1
#define KDHP_CRUISEKEYOPENFLTCLEARTIME_MS 1000U
#define KDHP_CRUISEKEYOPENFLTCONFIRMTIME_MS 1000U
#define KDHP_CRUISEKEYOPENFLTFAULTLEVEL_ENUM 2U
#define KDHP_CRUISEKEYOPENFLTHANDLERESPONSEBITS 1U
#define KDHP_CRUISEKEYOPENFLTPOWERLIMIT_PCT 100U
#define KDHP_CRUISEKEYOPENFLTSPDLIMIT  200U
#define KDHP_CRUISEKEYSHORTEDFLTALLOWRECOVERY_FLG 1
#define KDHP_CRUISEKEYSHORTEDFLTCLEARTIME_MS 1000U
#define KDHP_CRUISEKEYSHORTEDFLTCONFIRMTIME_MS 1000U
#define KDHP_CRUISEKEYSHORTEDFLTFAULTLEVEL_ENUM 2U
#define KDHP_CRUISEKEYSHORTEDFLTHANDLERESPONSEBITS 1U
#define KDHP_CRUISEKEYSHORTEDFLTPOWERLIMIT_PCT 100U
#define KDHP_CRUISEKEYSHORTEDFLTSPDLIMIT 200U
#define KDHP_DCCHRGPORTOVERTFAULTLEVEL_ENUM 2U
#define KDHP_DCCHRGPORTOVERTHANDLERESPONSEBITS 0U
#define KDHP_DCCHRGPORTOVERTPOWERLIMIT_PCT 100U
#define KDHP_DCCHRGPORTOVERTSPDLIMIT   200U
#define KDHP_DCDCFLT2ALLOWRECOVERY_FLG 1
#define KDHP_DCDCFLT2FAULTLEVEL_ENUM   2U
#define KDHP_DCDCFLT2HANDLERESPONSEBITS 8U
#define KDHP_DCDCFLT2POWERLIMIT_PCT    100U
#define KDHP_DCDCFLT2SPDLIMIT          200U
#define KDHP_DCDCLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_DCDCLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_DCDCLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_DCDCLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_DCDCLOSSCANNETSPDLIMIT    200U
#define KDHP_DCDCMISSINGALLOWRECOVERY_FLG 0
#define KDHP_DCDCMISSINGFAULTLEVEL_ENUM 2U
#define KDHP_DCDCMISSINGHANDLERESPONSEBITS 8U
#define KDHP_DCDCMISSINGPOWERLIMIT_PCT 100U
#define KDHP_DCDCMISSINGSPDLIMIT       200U
#define KDHP_DCDCMODEERRALLOWRECOVERY_FLG 1
#define KDHP_DCDCMODEERRFAULTLEVEL_ENUM 1U
#define KDHP_DCDCMODEERRHANDLERESPONSEBITS 0U
#define KDHP_DCDCMODEERRPOWERLIMIT_PCT 100U
#define KDHP_DCDCMODEERRSPDLIMIT       200U
#define KDHP_DCDCSTOPWORKTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_DCDCSTOPWORKTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_DCDCSTOPWORKTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_DCDCSTOPWORKTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_DCDCSTOPWORKTIMEOUTSPDLIMIT 200U
#define KDHP_DIDDATACHECKFAILEDALLOWRECOVERY_FLG 1
#define KDHP_DIDDATACHECKFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_DIDDATACHECKFAILEDHANDLERESPONSEBITS 0U
#define KDHP_DIDDATACHECKFAILEDPOWERLIMIT_PCT 100U
#define KDHP_DIDDATACHECKFAILEDSPDLIMIT 200U
#define KDHP_DIDDATADFLASHINVALIDALLOWRECOVERY_FLG 1
#define KDHP_DIDDATADFLASHINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_DIDDATADFLASHINVALIDHANDLERESPONSEBITS 0U
#define KDHP_DIDDATADFLASHINVALIDPOWERLIMIT_PCT 100U
#define KDHP_DIDDATADFLASHINVALIDSPDLIMIT 200U
#define KDHP_DIDDATAEEPROMINVALIDALLOWRECOVERY_FLG 1
#define KDHP_DIDDATAEEPROMINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_DIDDATAEEPROMINVALIDHANDLERESPONSEBITS 0U
#define KDHP_DIDDATAEEPROMINVALIDPOWERLIMIT_PCT 100U
#define KDHP_DIDDATAEEPROMINVALIDSPDLIMIT 200U
#define KDHP_EACLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_EACLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_EACLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_EACLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_EACLOSSCANNETSPDLIMIT     200U
#define KDHP_EBDWORKERRALLOWRECOVERY_FLG 1
#define KDHP_EBDWORKERRFAULTLEVEL_ENUM 2U
#define KDHP_EBDWORKERRHANDLERESPONSEBITS 0U
#define KDHP_EBDWORKERRPOWERLIMIT_PCT  100U
#define KDHP_EBDWORKERRSPDLIMIT        200U
#define KDHP_ECCLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_ECCLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_ECCLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_ECCLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_ECCLOSSCANNETSPDLIMIT     200U
#define KDHP_EHULOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_EHULOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_EHULOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_EHULOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_EHULOSSCANNETSPDLIMIT     200U
#define KDHP_EPBWORKERRALLOWRECOVERY_FLG 1
#define KDHP_EPBWORKERRFAULTLEVEL_ENUM 2U
#define KDHP_EPBWORKERRHANDLERESPONSEBITS 0U
#define KDHP_EPBWORKERRPOWERLIMIT_PCT  100U
#define KDHP_EPBWORKERRSPDLIMIT        200U
#define KDHP_EPSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_EPSLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_EPSLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_EPSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_EPSLOSSCANNETSPDLIMIT     200U
#define KDHP_EPSWORKERRALLOWRECOVERY_FLG 1
#define KDHP_EPSWORKERRFAULTLEVEL_ENUM 2U
#define KDHP_EPSWORKERRHANDLERESPONSEBITS 0U
#define KDHP_EPSWORKERRPOWERLIMIT_PCT  100U
#define KDHP_EPSWORKERRSPDLIMIT        200U
#define KDHP_ESCLAUTHENTICFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLAUTHENTICFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLAUTHENTICFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLAUTHENTICFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLAUTHENTICFAILEDSPDLIMIT 200U
#define KDHP_ESCLCHIPHWFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLCHIPHWFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLCHIPHWFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLCHIPHWFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLCHIPHWFAILEDSPDLIMIT  200U
#define KDHP_ESCLEEPROMFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLEEPROMFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLEEPROMFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLEEPROMFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLEEPROMFAILEDSPDLIMIT  200U
#define KDHP_ESCLLINCOMMFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLLINCOMMFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLLINCOMMFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLLINCOMMFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLLINCOMMFAILEDSPDLIMIT 200U
#define KDHP_ESCLLOCKGNDFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLLOCKGNDFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLLOCKGNDFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLLOCKGNDFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLLOCKGNDFAILEDSPDLIMIT 200U
#define KDHP_ESCLLOCKTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_ESCLLOCKTIMEOUTFAULTLEVEL_ENUM 2U
#define KDHP_ESCLLOCKTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_ESCLLOCKTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_ESCLLOCKTIMEOUTSPDLIMIT   200U
#define KDHP_ESCLMASTERIREQINVALIDALLOWRECOVERY_FLG 1
#define KDHP_ESCLMASTERIREQINVALIDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLMASTERIREQINVALIDHANDLERESPONSEBITS 0U
#define KDHP_ESCLMASTERIREQINVALIDPOWERLIMIT_PCT 100U
#define KDHP_ESCLMASTERIREQINVALIDSPDLIMIT 200U
#define KDHP_ESCLMASTERREQTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_ESCLMASTERREQTIMEOUTFAULTLEVEL_ENUM 2U
#define KDHP_ESCLMASTERREQTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_ESCLMASTERREQTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_ESCLMASTERREQTIMEOUTSPDLIMIT 200U
#define KDHP_ESCLMOTORDRIVERFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLMOTORDRIVERFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLMOTORDRIVERFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLMOTORDRIVERFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLMOTORDRIVERFAILEDSPDLIMIT 200U
#define KDHP_ESCLMOTORNOACTALLOWRECOVERY_FLG 1
#define KDHP_ESCLMOTORNOACTFAULTLEVEL_ENUM 2U
#define KDHP_ESCLMOTORNOACTHANDLERESPONSEBITS 0U
#define KDHP_ESCLMOTORNOACTPOWERLIMIT_PCT 100U
#define KDHP_ESCLMOTORNOACTSPDLIMIT    200U
#define KDHP_ESCLMOTOROVERLOADALLOWRECOVERY_FLG 1
#define KDHP_ESCLMOTOROVERLOADFAULTLEVEL_ENUM 2U
#define KDHP_ESCLMOTOROVERLOADHANDLERESPONSEBITS 0U
#define KDHP_ESCLMOTOROVERLOADPOWERLIMIT_PCT 100U
#define KDHP_ESCLMOTOROVERLOADSPDLIMIT 200U
#define KDHP_ESCLPWRSUPPLYFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLPWRSUPPLYFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLPWRSUPPLYFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLPWRSUPPLYFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLPWRSUPPLYFAILEDSPDLIMIT 200U
#define KDHP_ESCLSENSORHWFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLSENSORHWFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLSENSORHWFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLSENSORHWFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLSENSORHWFAILEDSPDLIMIT 200U
#define KDHP_ESCLSENSORSTSFAILEDALLOWRECOVERY_FLG 1
#define KDHP_ESCLSENSORSTSFAILEDFAULTLEVEL_ENUM 2U
#define KDHP_ESCLSENSORSTSFAILEDHANDLERESPONSEBITS 0U
#define KDHP_ESCLSENSORSTSFAILEDPOWERLIMIT_PCT 100U
#define KDHP_ESCLSENSORSTSFAILEDSPDLIMIT 200U
#define KDHP_ESCLUNLOCKTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_ESCLUNLOCKTIMEOUTFAULTLEVEL_ENUM 2U
#define KDHP_ESCLUNLOCKTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_ESCLUNLOCKTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_ESCLUNLOCKTIMEOUTSPDLIMIT 200U
#define KDHP_ESPWORKERRALLOWRECOVERY_FLG 1
#define KDHP_ESPWORKERRFAULTLEVEL_ENUM 2U
#define KDHP_ESPWORKERRHANDLERESPONSEBITS 0U
#define KDHP_ESPWORKERRPOWERLIMIT_PCT  100U
#define KDHP_ESPWORKERRSPDLIMIT        200U
#define KDHP_GEARSINGLENOTINAERAALLOWRECOVERY_FLG 1
#define KDHP_GEARSINGLENOTINAERACLEARTIME_MS 400U
#define KDHP_GEARSINGLENOTINAERACONFIRMTIME_MS 400U
#define KDHP_GEARSINGLENOTINAERAFAULTLEVEL_ENUM 2U
#define KDHP_GEARSINGLENOTINAERAHANDLERESPONSEBITS 0U
#define KDHP_GEARSINGLENOTINAERAPOWERLIMIT_PCT 100U
#define KDHP_GEARSINGLENOTINAERASPDLIMIT 200U
#define KDHP_GWLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_GWLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_GWLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_GWLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_GWLOSSCANNETSPDLIMIT      200U
#define KDHP_HISTDATACHECKFAILEDALLOWRECOVERY_FLG 1
#define KDHP_HISTDATACHECKFAILEDFAULTLEVEL_ENUM 1U
#define KDHP_HISTDATACHECKFAILEDHANDLERESPONSEBITS 0U
#define KDHP_HISTDATACHECKFAILEDPOWERLIMIT_PCT 100U
#define KDHP_HISTDATACHECKFAILEDSPDLIMIT 200U
#define KDHP_HVACTIVETIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_HVACTIVETIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_HVACTIVETIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_HVACTIVETIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_HVACTIVETIMEOUTSPDLIMIT   200U
#define KDHP_HVDCDCACTIVETIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_HVDCDCACTIVETIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_HVDCDCACTIVETIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_HVDCDCACTIVETIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_HVDCDCACTIVETIMEOUTSPDLIMIT 200U
#define KDHP_HVDOWNTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_HVDOWNTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_HVDOWNTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_HVDOWNTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_HVDOWNTIMEOUTSPDLIMIT     200U
#define KDHP_HVILERRCLEARTIME_MS       2000U
#define KDHP_HVILERRFAULTLEVEL_ENUM    2U
#define KDHP_HVILERRHANDLERESPONSEBITS 0U
#define KDHP_HVILERRPOWERLIMIT_PCT     100U
#define KDHP_HVILERRSPDLIMIT           200U
#define KDHP_HVPWRUPTIMEOUTALLOWRECOVERY_FLG 0
#define KDHP_HVPWRUPTIMEOUTCLEARTIME_MS 1U
#define KDHP_HVPWRUPTIMEOUTCONFIRMTIME_MS 60U
#define KDHP_HVPWRUPTIMEOUTFAULTLEVEL_ENUM 3U
#define KDHP_HVPWRUPTIMEOUTHANDLERESPONSEBITS 8191U
#define KDHP_HVPWRUPTIMEOUTPOWERLIMIT_PCT 0U
#define KDHP_HVPWRUPTIMEOUTSPDLIMIT    0U
#define KDHP_HVUPTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_HVUPTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_HVUPTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_HVUPTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_HVUPTIMEOUTSPDLIMIT       200U
#define KDHP_ICHRGERRORALLOWRECOVERY_FLG 1
#define KDHP_ICHRGERRORFAULTLEVEL_ENUM 1U
#define KDHP_ICHRGERRORHANDLERESPONSEBITS 0U
#define KDHP_ICHRGERRORPOWERLIMIT_PCT  100U
#define KDHP_ICHRGERRORSPDLIMIT        200U
#define KDHP_ICMLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_ICMLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_ICMLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_ICMLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_ICMLOSSCANNETSPDLIMIT     200U
#define KDHP_ICMVEHSPDCHKINVALIDALLOWRECOVERY_FLG 1
#define KDHP_ICMVEHSPDCHKINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_ICMVEHSPDCHKINVALIDHANDLERESPONSEBITS 0U
#define KDHP_ICMVEHSPDCHKINVALIDPOWERLIMIT_PCT 100U
#define KDHP_ICMVEHSPDCHKINVALIDSPDLIMIT 200U
#define KDHP_IGN1FEEDVOLTFLTALLOWRECOVERY_FLG 1
#define KDHP_IGN1FEEDVOLTFLTFAULTLEVEL_ENUM 2U
#define KDHP_IGN1FEEDVOLTFLTHANDLERESPONSEBITS 0U
#define KDHP_IGN1FEEDVOLTFLTPOWERLIMIT_PCT 100U
#define KDHP_IGN1FEEDVOLTFLTSPDLIMIT   200U
#define KDHP_IGN2FEEDVOLTFLTALLOWRECOVERY_FLG 1
#define KDHP_IGN2FEEDVOLTFLTFAULTLEVEL_ENUM 2U
#define KDHP_IGN2FEEDVOLTFLTHANDLERESPONSEBITS 0U
#define KDHP_IGN2FEEDVOLTFLTPOWERLIMIT_PCT 100U
#define KDHP_IGN2FEEDVOLTFLTSPDLIMIT   200U
#define KDHP_LVUPBMSPWRUPALLWTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_LVUPBMSPWRUPALLWTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_LVUPBMSPWRUPALLWTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_LVUPBMSPWRUPALLWTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_LVUPBMSPWRUPALLWTIMEOUTSPDLIMIT 200U
#define KDHP_LVUPBMSTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_LVUPBMSTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_LVUPBMSTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_LVUPBMSTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_LVUPBMSTIMEOUTSPDLIMIT    200U
#define KDHP_LVUPDCDCTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_LVUPDCDCTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_LVUPDCDCTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_LVUPDCDCTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_LVUPDCDCTIMEOUTSPDLIMIT   200U
#define KDHP_LVUPMCUTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_LVUPMCUTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_LVUPMCUTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_LVUPMCUTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_LVUPMCUTIMEOUTSPDLIMIT    200U
#define KDHP_MCUCANBUSOFFALLOWRECOVERY_FLG 1
#define KDHP_MCUCANBUSOFFFAULTLEVEL_ENUM 2U
#define KDHP_MCUCANBUSOFFHANDLERESPONSEBITS 0U
#define KDHP_MCUCANBUSOFFPOWERLIMIT_PCT 100U
#define KDHP_MCUCANBUSOFFSPDLIMIT      200U
#define KDHP_MCUCANCOMALLOWRECOVERY_FLG 1
#define KDHP_MCUCANCOMFAULTLEVEL_ENUM  2U
#define KDHP_MCUCANCOMHANDLERESPONSEBITS 0U
#define KDHP_MCUCANCOMSPDLIMIT         8U
#define KDHP_MCUCHIPPOWERFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUCHIPPOWERFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUCHIPPOWERFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUCHIPPOWERFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUCHIPPOWERFLTSPDLIMIT   200U
#define KDHP_MCUCOVERFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUCOVERFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUCOVERFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUCOVERFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUCOVERFLTSPDLIMIT       200U
#define KDHP_MCUCOVERWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUCOVERWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUCOVERWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUCOVERWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUCOVERWARNSPDLIMIT      200U
#define KDHP_MCUDCCRRTOVERREDUNDALLOWRECOVERY_FLG 0
#define KDHP_MCUDCCRRTOVERREDUNDCLEARTIME_MS 60U
#define KDHP_MCUDCCRRTOVERREDUNDCONFIRMTIME_MS 60U
#define KDHP_MCUDCCRRTOVERREDUNDFAULTLEVEL_ENUM 3U
#define KDHP_MCUDCCRRTOVERREDUNDHANDLERESPONSEBITS 8191U
#define KDHP_MCUDCCRRTOVERREDUNDPOWERLIMIT_PCT 0U
#define KDHP_MCUDCCRRTOVERREDUNDSPDLIMIT 0U
#define KDHP_MCUDCUOVERUFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUOVERUFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUOVERUFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUOVERUFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUOVERUFLTSPDLIMIT    200U
#define KDHP_MCUDCUOVERUHWFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUOVERUHWFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUOVERUHWFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUOVERUHWFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUOVERUHWFLTSPDLIMIT  200U
#define KDHP_MCUDCUOVERUREDUNDALLOWRECOVERY_FLG 0
#define KDHP_MCUDCUOVERUREDUNDCLEARTIME_MS 60U
#define KDHP_MCUDCUOVERUREDUNDCONFIRMTIME_MS 60U
#define KDHP_MCUDCUOVERUREDUNDFAULTLEVEL_ENUM 3U
#define KDHP_MCUDCUOVERUREDUNDHANDLERESPONSEBITS 8191U
#define KDHP_MCUDCUOVERUREDUNDPOWERLIMIT_PCT 0U
#define KDHP_MCUDCUOVERUREDUNDSPDLIMIT 0U
#define KDHP_MCUDCUOVERUWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUOVERUWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUOVERUWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUOVERUWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUOVERUWARNSPDLIMIT   200U
#define KDHP_MCUDCUSHOCIRCALLOWRECOVERY_FLG 0
#define KDHP_MCUDCUSHOCIRCFAULTLEVEL_ENUM 3U
#define KDHP_MCUDCUSHOCIRCHANDLERESPONSEBITS 8191U
#define KDHP_MCUDCUSHOCIRCPOWERLIMIT_PCT 0U
#define KDHP_MCUDCUSHOCIRCSPDLIMIT     0U
#define KDHP_MCUDCUSNSRRATIALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUSNSRRATIFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUSNSRRATIHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUSNSRRATIPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUSNSRRATISPDLIMIT    200U
#define KDHP_MCUDCUUNDERUFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUUNDERUFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUUNDERUFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUUNDERUFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUUNDERUFLTSPDLIMIT   200U
#define KDHP_MCUDCUUNDERUWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUDCUUNDERUWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUDCUUNDERUWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUDCUUNDERUWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUDCUUNDERUWARNSPDLIMIT  200U
#define KDHP_MCUDISCHARGETIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_MCUDISCHARGETIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_MCUDISCHARGETIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_MCUDISCHARGETIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_MCUDISCHARGETIMEOUTSPDLIMIT 200U
#define KDHP_MCUDISCHRGALLOWRECOVERY_FLG 1
#define KDHP_MCUDISCHRGFAULTLEVEL_ENUM 2U
#define KDHP_MCUDISCHRGHANDLERESPONSEBITS 0U
#define KDHP_MCUDISCHRGPOWERLIMIT_PCT  100U
#define KDHP_MCUDISCHRGSPDLIMIT        200U
#define KDHP_MCUELECMOTOVERCRRTALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTOVERCRRTFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTOVERCRRTHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTOVERCRRTSPDLIMIT 8U
#define KDHP_MCUELECMOTOVERSPDFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTOVERSPDFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTOVERSPDFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTOVERSPDFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTOVERSPDFLTSPDLIMIT 200U
#define KDHP_MCUELECMOTOVERSPDWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTOVERSPDWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTOVERSPDWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTOVERSPDWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTOVERSPDWARNSPDLIMIT 200U
#define KDHP_MCUELECMOTOVERTFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTOVERTFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTOVERTFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTOVERTFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTOVERTFLTSPDLIMIT 200U
#define KDHP_MCUELECMOTOVERTWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTOVERTWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTOVERTWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTOVERTWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTOVERTWARNSPDLIMIT 200U
#define KDHP_MCUELECMOTRESLVALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTRESLVFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTRESLVHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTRESLVPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTRESLVSPDLIMIT   200U
#define KDHP_MCUELECMOTSTOPTURNALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTSTOPTURNFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTSTOPTURNHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTSTOPTURNPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTSTOPTURNSPDLIMIT 200U
#define KDHP_MCUELECMOTTSNSRRATIALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTTSNSRRATIFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTTSNSRRATIHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTTSNSRRATIPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTTSNSRRATISPDLIMIT 200U
#define KDHP_MCUELECMOTUNDERTALLOWRECOVERY_FLG 1
#define KDHP_MCUELECMOTUNDERTFAULTLEVEL_ENUM 2U
#define KDHP_MCUELECMOTUNDERTHANDLERESPONSEBITS 0U
#define KDHP_MCUELECMOTUNDERTPOWERLIMIT_PCT 100U
#define KDHP_MCUELECMOTUNDERTSPDLIMIT  200U
#define KDHP_MCUEXITTORQTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_MCUEXITTORQTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_MCUEXITTORQTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_MCUEXITTORQTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_MCUEXITTORQTIMEOUTSPDLIMIT 200U
#define KDHP_MCUFLT1ALLOWRECOVERY_FLG  1
#define KDHP_MCUFLT1FAULTLEVEL_ENUM    1U
#define KDHP_MCUFLT1HANDLERESPONSEBITS 0U
#define KDHP_MCUFLT1POWERLIMIT_PCT     100U
#define KDHP_MCUFLT1SPDLIMIT           200U
#define KDHP_MCUFLT2ALLOWRECOVERY_FLG  1
#define KDHP_MCUFLT2FAULTLEVEL_ENUM    2U
#define KDHP_MCUFLT2HANDLERESPONSEBITS 0U
#define KDHP_MCUFLT2POWERLIMIT_PCT     100U
#define KDHP_MCUFLT2SPDLIMIT           200U
#define KDHP_MCUFLT3ALLOWRECOVERY_FLG  1
#define KDHP_MCUFLT3FAULTLEVEL_ENUM    2U
#define KDHP_MCUFLT3HANDLERESPONSEBITS 0U
#define KDHP_MCUFLT3POWERLIMIT_PCT     100U
#define KDHP_MCUFLT3SPDLIMIT           200U
#define KDHP_MCUFLTUNMATCHALLOWRECOVERY_FLG 1
#define KDHP_MCUFLTUNMATCHFAULTLEVEL_ENUM 1U
#define KDHP_MCUFLTUNMATCHHANDLERESPONSEBITS 0U
#define KDHP_MCUFLTUNMATCHPOWERLIMIT_PCT 100U
#define KDHP_MCUFLTUNMATCHSPDLIMIT     200U
#define KDHP_MCUHVACTIVETIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_MCUHVACTIVETIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_MCUHVACTIVETIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_MCUHVACTIVETIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_MCUHVACTIVETIMEOUTSPDLIMIT 200U
#define KDHP_MCUHWCURROVERALLOWRECOVERY_FLG 0
#define KDHP_MCUHWCURROVERFAULTLEVEL_ENUM 3U
#define KDHP_MCUHWCURROVERHANDLERESPONSEBITS 8191U
#define KDHP_MCUHWCURROVERPOWERLIMIT_PCT 0U
#define KDHP_MCUHWCURROVERREDUNDALLOWRECOVERY_FLG 0
#define KDHP_MCUHWCURROVERREDUNDCLEARTIME_MS 400U
#define KDHP_MCUHWCURROVERREDUNDCONFIRMTIME_MS 3000U
#define KDHP_MCUHWCURROVERREDUNDFAULTLEVEL_ENUM 3U
#define KDHP_MCUHWCURROVERREDUNDHANDLERESPONSEBITS 8191U
#define KDHP_MCUHWCURROVERREDUNDPOWERLIMIT_PCT 0U
#define KDHP_MCUHWCURROVERREDUNDSPDLIMIT 0U
#define KDHP_MCUHWCURROVERSPDLIMIT     0U
#define KDHP_MCUHWSAMPLINGFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUHWSAMPLINGFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUHWSAMPLINGFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUHWSAMPLINGFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUHWSAMPLINGFLTSPDLIMIT  200U
#define KDHP_MCUIGBTHWALLOWRECOVERY_FLG 0
#define KDHP_MCUIGBTHWFAULTLEVEL_ENUM  3U
#define KDHP_MCUIGBTHWHANDLERESPONSEBITS 8191U
#define KDHP_MCUIGBTHWPOWERLIMIT_PCT   0U
#define KDHP_MCUIGBTHWSPDLIMIT         0U
#define KDHP_MCUIGBTOVERTFLTALLOWRECOVERY_FLG 1
#define KDHP_MCUIGBTOVERTFLTFAULTLEVEL_ENUM 2U
#define KDHP_MCUIGBTOVERTFLTHANDLERESPONSEBITS 0U
#define KDHP_MCUIGBTOVERTFLTPOWERLIMIT_PCT 100U
#define KDHP_MCUIGBTOVERTFLTSPDLIMIT   200U
#define KDHP_MCUIGBTOVERTWARNALLOWRECOVERY_FLG 1
#define KDHP_MCUIGBTOVERTWARNFAULTLEVEL_ENUM 2U
#define KDHP_MCUIGBTOVERTWARNHANDLERESPONSEBITS 0U
#define KDHP_MCUIGBTOVERTWARNPOWERLIMIT_PCT 100U
#define KDHP_MCUIGBTOVERTWARNSPDLIMIT  200U
#define KDHP_MCUIGBTPHASETCHECKERRALLOWRECOVERY_FLG 1
#define KDHP_MCUIGBTPHASETCHECKERRFAULTLEVEL_ENUM 1U
#define KDHP_MCUIGBTPHASETCHECKERRHANDLERESPONSEBITS 0U
#define KDHP_MCUIGBTPHASETCHECKERRPOWERLIMIT_PCT 100U
#define KDHP_MCUIGBTPHASETCHECKERRSPDLIMIT 200U
#define KDHP_MCUIGBTUNDERTALLOWRECOVERY_FLG 1
#define KDHP_MCUIGBTUNDERTFAULTLEVEL_ENUM 2U
#define KDHP_MCUIGBTUNDERTHANDLERESPONSEBITS 0U
#define KDHP_MCUIGBTUNDERTPOWERLIMIT_PCT 100U
#define KDHP_MCUIGBTUNDERTSPDLIMIT     200U
#define KDHP_MCULOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_MCULOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_MCULOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_MCULOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_MCULOSSCANNETSPDLIMIT     200U
#define KDHP_MCULOWBATTUNDERUALLOWRECOVERY_FLG 0
#define KDHP_MCULOWBATTUNDERUFAULTLEVEL_ENUM 3U
#define KDHP_MCULOWBATTUNDERUHANDLERESPONSEBITS 8191U
#define KDHP_MCULOWBATTUNDERUPOWERLIMIT_PCT 0U
#define KDHP_MCULOWBATTUNDERUSPDLIMIT  0U
#define KDHP_MCUMISSINGFAULTLEVEL_ENUM 2U
#define KDHP_MCUMISSINGHANDLERESPONSEBITS 0U
#define KDHP_MCUMISSINGPOWERLIMIT_PCT  100U
#define KDHP_MCUMISSINGSPDLIMIT        200U
#define KDHP_MCUMODEERRALLOWRECOVERY_FLG 1
#define KDHP_MCUMODEERRFAULTLEVEL_ENUM 1U
#define KDHP_MCUMODEERRHANDLERESPONSEBITS 0U
#define KDHP_MCUMODEERRPOWERLIMIT_PCT  100U
#define KDHP_MCUMODEERRSPDLIMIT        200U
#define KDHP_MCUMOTTUPRATEALLOWRECOVERY_FLG 1
#define KDHP_MCUMOTTUPRATECLEARTIME_MS 6000U
#define KDHP_MCUMOTTUPRATECONFIRMTIME_MS 5000U
#define KDHP_MCUMOTTUPRATEFAULTLEVEL_ENUM 2U
#define KDHP_MCUMOTTUPRATEHANDLERESPONSEBITS 0U
#define KDHP_MCUMOTTUPRATEPOWERLIMIT_PCT 20U
#define KDHP_MCUMOTTUPRATESPDLIMIT     8U
#define KDHP_MCUOVERTALLOWRECOVERY_FLG 1
#define KDHP_MCUOVERTFAULTLEVEL_ENUM   2U
#define KDHP_MCUOVERTHANDLERESPONSEBITS 0U
#define KDHP_MCUOVERTPOWERLIMIT_PCT    100U
#define KDHP_MCUOVERTSPDLIMIT          200U
#define KDHP_MCUPHAACCRRTSNSRRATIALLOWRECOVERY_FLG 1
#define KDHP_MCUPHAACCRRTSNSRRATIFAULTLEVEL_ENUM 2U
#define KDHP_MCUPHAACCRRTSNSRRATIHANDLERESPONSEBITS 0U
#define KDHP_MCUPHAACCRRTSNSRRATIPOWERLIMIT_PCT 100U
#define KDHP_MCUPHAACCRRTSNSRRATISPDLIMIT 200U
#define KDHP_MCUPHASELOSSALLOWRECOVERY_FLG 1
#define KDHP_MCUPHASELOSSFAULTLEVEL_ENUM 2U
#define KDHP_MCUPHASELOSSHANDLERESPONSEBITS 0U
#define KDHP_MCUPHASELOSSPOWERLIMIT_PCT 100U
#define KDHP_MCUPHASELOSSSPDLIMIT      200U
#define KDHP_MCUPWRMODREDUNDALLOWRECOVERY_FLG 0
#define KDHP_MCUPWRMODREDUNDCLEARTIME_MS 400U
#define KDHP_MCUPWRMODREDUNDCONFIRMTIME_MS 3000U
#define KDHP_MCUPWRMODREDUNDFAULTLEVEL_ENUM 3U
#define KDHP_MCUPWRMODREDUNDHANDLERESPONSEBITS 8191U
#define KDHP_MCUPWRMODREDUNDPOWERLIMIT_PCT 0U
#define KDHP_MCUPWRMODREDUNDSPDLIMIT   0U
#define KDHP_MCUSPDINVALIDALLOWRECOVERY_FLG 1
#define KDHP_MCUSPDINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_MCUSPDINVALIDHANDLERESPONSEBITS 0U
#define KDHP_MCUSPDINVALIDPOWERLIMIT_PCT 100U
#define KDHP_MCUSPDINVALIDSPDLIMIT     200U
#define KDHP_MCUTORQCHECKERRALLOWRECOVERY_FLG 1
#define KDHP_MCUTORQCHECKERRFAULTLEVEL_ENUM 2U
#define KDHP_MCUTORQCHECKERRHANDLERESPONSEBITS 0U
#define KDHP_MCUTORQCHECKERRPOWERLIMIT_PCT 100U
#define KDHP_MCUTORQCHECKERRSPDLIMIT   200U
#define KDHP_MCUTORQOUTERRANGEALLOWRECOVERY_FLG 1
#define KDHP_MCUTORQOUTERRANGEFAULTLEVEL_ENUM 1U
#define KDHP_MCUTORQOUTERRANGEHANDLERESPONSEBITS 0U
#define KDHP_MCUTORQOUTERRANGEPOWERLIMIT_PCT 100U
#define KDHP_MCUTORQOUTERRANGESPDLIMIT 200U
#define KDHP_MCUTRQINVALIDALLOWRECOVERY_FLG 1
#define KDHP_MCUTRQINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_MCUTRQINVALIDHANDLERESPONSEBITS 0U
#define KDHP_MCUTRQINVALIDPOWERLIMIT_PCT 100U
#define KDHP_MCUTRQINVALIDSPDLIMIT     200U
#define KDHP_MCUTSNSRRATIALLOWRECOVERY_FLG 1
#define KDHP_MCUTSNSRRATIFAULTLEVEL_ENUM 2U
#define KDHP_MCUTSNSRRATIHANDLERESPONSEBITS 0U
#define KDHP_MCUTSNSRRATIPOWERLIMIT_PCT 100U
#define KDHP_MCUTSNSRRATISPDLIMIT      200U
#define KDHP_MCUVERSIONMISMATCHALLOWRECOVERY_FLG 0
#define KDHP_MCUVERSIONMISMATCHFAULTLEVEL_ENUM 3U
#define KDHP_MCUVERSIONMISMATCHHANDLERESPONSEBITS 8191U
#define KDHP_MCUVERSIONMISMATCHPOWERLIMIT_PCT 0U
#define KDHP_MCUVERSIONMISMATCHSPDLIMIT 0U
#define KDHP_NMLIPHOMEALLOWRECOVERY_FLG 1
#define KDHP_NMLIPHOMECLEARTIME_MS     1U
#define KDHP_NMLIPHOMECONFIRMTIME_MS   2000U
#define KDHP_NMLIPHOMEFAULTLEVEL_ENUM  1U
#define KDHP_NMLIPHOMEHANDLERESPONSEBITS 0U
#define KDHP_NMLIPHOMEPOWERLIMIT_PCT   100U
#define KDHP_NMLIPHOMESPDLIMIT         200U
#define KDHP_OBCFLT2ALLOWRECOVERY_FLG  1
#define KDHP_OBCFLT2FAULTLEVEL_ENUM    2U
#define KDHP_OBCFLT2HANDLERESPONSEBITS 0U
#define KDHP_OBCFLT2POWERLIMIT_PCT     100U
#define KDHP_OBCFLT2SPDLIMIT           200U
#define KDHP_OBCFLT3ALLOWRECOVERY_FLG  0
#define KDHP_OBCFLT3FAULTLEVEL_ENUM    3U
#define KDHP_OBCFLT3HANDLERESPONSEBITS 8191U
#define KDHP_OBCFLT3POWERLIMIT_PCT     0U
#define KDHP_OBCFLT3SPDLIMIT           0U
#define KDHP_OBCLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_OBCLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_OBCLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_OBCLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_OBCLOSSCANNETSPDLIMIT     200U
#define KDHP_OBCMISSINGFAULTLEVEL_ENUM 2U
#define KDHP_OBCMISSINGHANDLERESPONSEBITS 1024U
#define KDHP_OBCMISSINGPOWERLIMIT_PCT  100U
#define KDHP_OBCMISSINGSPDLIMIT        200U
#define KDHP_OBCWAKEUPTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_OBCWAKEUPTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_OBCWAKEUPTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_OBCWAKEUPTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_OBCWAKEUPTIMEOUTSPDLIMIT  200U
#define KDHP_OVERDIAGNVOLTALLOWRECOVERY_FLG 1
#define KDHP_OVERDIAGNVOLTCLEARTIME_MS 1500U
#define KDHP_OVERDIAGNVOLTCONFIRMTIME_MS 2000U
#define KDHP_OVERDIAGNVOLTFAULTLEVEL_ENUM 1U
#define KDHP_OVERDIAGNVOLTHANDLERESPONSEBITS 0U
#define KDHP_OVERDIAGNVOLTPOWERLIMIT_PCT 100U
#define KDHP_OVERDIAGNVOLTSPDLIMIT     200U
#define KDHP_PEPSFAILEDALLOWRECOVERY_FLG 1
#define KDHP_PEPSFAILEDFAULTLEVEL_ENUM 1U
#define KDHP_PEPSFAILEDHANDLERESPONSEBITS 0U
#define KDHP_PEPSFAILEDPOWERLIMIT_PCT  100U
#define KDHP_PEPSFAILEDSPDLIMIT        200U
#define KDHP_PTBUSOFFALLOWRECOVERY_FLG 1
#define KDHP_PTBUSOFFFAULTLEVEL_ENUM   1U
#define KDHP_PTBUSOFFHANDLERESPONSEBITS 0U
#define KDHP_PTBUSOFFPOWERLIMIT_PCT    100U
#define KDHP_PTBUSOFFSPDLIMIT          200U
#define KDHP_PTCANLOSSALLOWRECOVERY_FLG 0
#define KDHP_PTCANLOSSFAULTLEVEL_ENUM  3U
#define KDHP_PTCANLOSSHANDLERESPONSEBITS 8191U
#define KDHP_PTCANLOSSPOWERLIMIT_PCT   0U
#define KDHP_PTCANLOSSSPDLIMIT         0U
#define KDHP_REGENABNORMALALLOWRECOVERY_FLG 1
#define KDHP_REGENABNORMALCLEARTIME_MS 1U
#define KDHP_REGENABNORMALFAULTLEVEL_ENUM 1U
#define KDHP_REGENABNORMALHANDLERESPONSEBITS 0U
#define KDHP_REGENABNORMALPOWERLIMIT_PCT 100U
#define KDHP_REGENABNORMALSPDLIMIT     200U
#define KDHP_SCRACTUALSPEEDLOWALLOWRECOVERY_FLG 1
#define KDHP_SCRACTUALSPEEDLOWFAULTLEVEL_ENUM 1U
#define KDHP_SCRACTUALSPEEDLOWHANDLERESPONSEBITS 0U
#define KDHP_SCRACTUALSPEEDLOWPOWERLIMIT_PCT 100U
#define KDHP_SCRACTUALSPEEDLOWSPDLIMIT 200U
#define KDHP_SCRTARGETSPDUNFOLLOWEDALLOWRECOVERY_FLG 1
#define KDHP_SCRTARGETSPDUNFOLLOWEDFAULTLEVEL_ENUM 1U
#define KDHP_SCRTARGETSPDUNFOLLOWEDHANDLERESPONSEBITS 0U
#define KDHP_SCRTARGETSPDUNFOLLOWEDPOWERLIMIT_PCT 100U
#define KDHP_SCRTARGETSPDUNFOLLOWEDSPDLIMIT 200U
#define KDHP_SHIFTKNOBCHECKTIMEOUTALLOWRECOVERY_FLG 1
#define KDHP_SHIFTKNOBCHECKTIMEOUTFAULTLEVEL_ENUM 1U
#define KDHP_SHIFTKNOBCHECKTIMEOUTHANDLERESPONSEBITS 0U
#define KDHP_SHIFTKNOBCHECKTIMEOUTPOWERLIMIT_PCT 100U
#define KDHP_SHIFTKNOBCHECKTIMEOUTSPDLIMIT 200U
#define KDHP_SPEEDINVALIDALLOWRECOVERY_FLG 1
#define KDHP_SPEEDINVALIDCLEARTIME_MS  1U
#define KDHP_SPEEDINVALIDCONFIRMTIME_MS 500U
#define KDHP_SPEEDINVALIDFAULTLEVEL_ENUM 2U
#define KDHP_SPEEDINVALIDHANDLERESPONSEBITS 0U
#define KDHP_SPEEDINVALIDPOWERLIMIT_PCT 20U
#define KDHP_SPEEDINVALIDSPDLIMIT      200U
#define KDHP_SRSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_SRSLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_SRSLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_SRSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_SRSLOSSCANNETSPDLIMIT     200U
#define KDHP_SRSMISSINGALLOWRECOVERY_FLG 1
#define KDHP_SRSMISSINGCLEARTIME_MS    1U
#define KDHP_SRSMISSINGCONFIRMTIME_MS  1500U
#define KDHP_SRSMISSINGFAULTLEVEL_ENUM 1U
#define KDHP_SRSMISSINGHANDLERESPONSEBITS 0U
#define KDHP_SRSMISSINGPOWERLIMIT_PCT  100U
#define KDHP_SRSMISSINGSPDLIMIT        200U
#define KDHP_SSBSYNCFLTALLOWRECOVERY_FLG 1
#define KDHP_SSBSYNCFLTFAULTLEVEL_ENUM 1U
#define KDHP_SSBSYNCFLTHANDLERESPONSEBITS 0U
#define KDHP_SSBSYNCFLTPOWERLIMIT_PCT  100U
#define KDHP_SSBSYNCFLTSPDLIMIT        200U
#define KDHP_TBOXLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_TBOXLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_TBOXLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_TBOXLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_TBOXLOSSCANNETSPDLIMIT    200U
#define KDHP_TMSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_TMSLOSSCANNETFAULTLEVEL_ENUM 1U
#define KDHP_TMSLOSSCANNETHANDLERESPONSEBITS 0U
#define KDHP_TMSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_TMSLOSSCANNETSPDLIMIT     200U
#define KDHP_TMSREQINVALIDALLOWRECOVERY_FLG 1
#define KDHP_TMSREQINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_TMSREQINVALIDHANDLERESPONSEBITS 0U
#define KDHP_TMSREQINVALIDPOWERLIMIT_PCT 100U
#define KDHP_TMSREQINVALIDSPDLIMIT     200U
#define KDHP_UNDERDIAGNVOLTALLOWRECOVERY_FLG 1
#define KDHP_UNDERDIAGNVOLTCLEARTIME_MS 1500U
#define KDHP_UNDERDIAGNVOLTCONFIRMTIME_MS 2000U
#define KDHP_UNDERDIAGNVOLTFAULTLEVEL_ENUM 1U
#define KDHP_UNDERDIAGNVOLTHANDLERESPONSEBITS 0U
#define KDHP_UNDERDIAGNVOLTPOWERLIMIT_PCT 100U
#define KDHP_UNDERDIAGNVOLTSPDLIMIT    200U
#define KDHP_VACHZFLT1ALLOWRECOVERY_FLG 1
#define KDHP_VACHZFLT1CLEARTIME_MS     4000U
#define KDHP_VACHZFLT1CONFIRMTIME_MS   2000U
#define KDHP_VACHZFLT1FAULTLEVEL_ENUM  2U
#define KDHP_VACHZFLT1HANDLERESPONSEBITS 0U
#define KDHP_VACHZFLT1POWERLIMIT_PCT   100U
#define KDHP_VACHZFLT1SPDLIMIT         200U
#define KDHP_VACHZFLT2ALLOWRECOVERY_FLG 1
#define KDHP_VACHZFLT2CLEARTIME_MS     4000U
#define KDHP_VACHZFLT2CONFIRMTIME_MS   2000U
#define KDHP_VACHZFLT2FAULTLEVEL_ENUM  2U
#define KDHP_VACHZFLT2HANDLERESPONSEBITS 0U
#define KDHP_VACHZFLT2POWERLIMIT_PCT   100U
#define KDHP_VACHZFLT2SPDLIMIT         200U
#define KDHP_VACPUMPHARDWIREALLOWRECOVERY_FLG 1
#define KDHP_VACPUMPHARDWIRECLEARTIME_MS 4000U
#define KDHP_VACPUMPHARDWIRECONFIRMTIME_MS 2000U
#define KDHP_VACPUMPHARDWIREFAULTLEVEL_ENUM 2U
#define KDHP_VACPUMPHARDWIREHANDLERESPONSEBITS 0U
#define KDHP_VACPUMPHARDWIREPOWERLIMIT_PCT 100U
#define KDHP_VACPUMPHARDWIRESPDLIMIT   200U
#define KDHP_VCUCHRGREQLIMFACALLOWRECOVERY_FLG 1
#define KDHP_VCUCHRGREQLIMFACFAULTLEVEL_ENUM 1U
#define KDHP_VCUCHRGREQLIMFACHANDLERESPONSEBITS 0U
#define KDHP_VCUCHRGREQLIMFACPOWERLIMIT_PCT 100U
#define KDHP_VCUCHRGREQLIMFACSPDLIMIT  200U
#define KDHP_VCUHWCANNETLINEOFFALLOWRECOVERY_FLG 0
#define KDHP_VCUHWCANNETLINEOFFCLEARTIME_MS 1U
#define KDHP_VCUHWCANNETLINEOFFCONFIRMTIME_MS 1000U
#define KDHP_VCUHWCANNETLINEOFFFAULTLEVEL_ENUM 3U
#define KDHP_VCUHWCANNETLINEOFFHANDLERESPONSEBITS 8191U
#define KDHP_VCUHWCANNETLINEOFFPOWERLIMIT_PCT 0U
#define KDHP_VCUHWCANNETLINEOFFSPDLIMIT 0U
#define KDHP_VCUHWHS1FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWHS1FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWHS1FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWHS1FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWHS1FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWHS1FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWHS1FLTSPDLIMIT       200U
#define KDHP_VCUHWLS1FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS1FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS1FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS1FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS1FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS1FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS1FLTSPDLIMIT       200U
#define KDHP_VCUHWLS2FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS2FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS2FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS2FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS2FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS2FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS2FLTSPDLIMIT       200U
#define KDHP_VCUHWLS3FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS3FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS3FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS3FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS3FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS3FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS3FLTSPDLIMIT       200U
#define KDHP_VCUHWLS4FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS4FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS4FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS4FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS4FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS4FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS4FLTSPDLIMIT       200U
#define KDHP_VCUHWLS5FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS5FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS5FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS5FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS5FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS5FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS5FLTSPDLIMIT       200U
#define KDHP_VCUHWLS6FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS6FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS6FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS6FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS6FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS6FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS6FLTSPDLIMIT       200U
#define KDHP_VCUHWLS7FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS7FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS7FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS7FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS7FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS7FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS7FLTSPDLIMIT       200U
#define KDHP_VCUHWLS8FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLS8FLTCLEARTIME_MS   2000U
#define KDHP_VCUHWLS8FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLS8FLTFAULTLEVEL_ENUM 1U
#define KDHP_VCUHWLS8FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLS8FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLS8FLTSPDLIMIT       200U
#define KDHP_VCUHWLSESCLPWRFLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLSESCLPWRFLTCLEARTIME_MS 2000U
#define KDHP_VCUHWLSESCLPWRFLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLSESCLPWRFLTFAULTLEVEL_ENUM 2U
#define KDHP_VCUHWLSESCLPWRFLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLSESCLPWRFLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLSESCLPWRFLTSPDLIMIT 200U
#define KDHP_VCUHWLSIGN1FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLSIGN1FLTCLEARTIME_MS 2000U
#define KDHP_VCUHWLSIGN1FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLSIGN1FLTFAULTLEVEL_ENUM 2U
#define KDHP_VCUHWLSIGN1FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLSIGN1FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLSIGN1FLTSPDLIMIT    200U
#define KDHP_VCUHWLSIGN2FLTALLOWRECOVERY_FLG 1
#define KDHP_VCUHWLSIGN2FLTCLEARTIME_MS 2000U
#define KDHP_VCUHWLSIGN2FLTCONFIRMTIME_MS 1000U
#define KDHP_VCUHWLSIGN2FLTFAULTLEVEL_ENUM 2U
#define KDHP_VCUHWLSIGN2FLTHANDLERESPONSEBITS 0U
#define KDHP_VCUHWLSIGN2FLTPOWERLIMIT_PCT 100U
#define KDHP_VCUHWLSIGN2FLTSPDLIMIT    200U
#define KDHP_VEHCRASHALLOWRECOVERY_FLG 0
#define KDHP_VEHCRASHFAULTLEVEL_ENUM   4U
#define KDHP_VEHCRASHHANDLERESPONSEBITS 16383U
#define KDHP_VEHCRASHHARDWARECANSIGNALALLOWRECOVERY_FLG 1
#define KDHP_VEHCRASHHARDWARECANSIGNALCLEARTIME_MS 400U
#define KDHP_VEHCRASHHARDWARECANSIGNALCONFIRMTIME_MS 1500U
#define KDHP_VEHCRASHHARDWARECANSIGNALFAULTLEVEL_ENUM 2U
#define KDHP_VEHCRASHHARDWARECANSIGNALHANDLERESPONSEBITS 0U
#define KDHP_VEHCRASHHARDWARECANSIGNALPOWERLIMIT_PCT 100U
#define KDHP_VEHCRASHHARDWARECANSIGNALSPDLIMIT 200U
#define KDHP_VEHCRASHHARDWARESIGNALALLOWRECOVERY_FLG 1
#define KDHP_VEHCRASHHARDWARESIGNALCLEARTIME_MS 400U
#define KDHP_VEHCRASHHARDWARESIGNALCONFIRMTIME_MS 2000U
#define KDHP_VEHCRASHHARDWARESIGNALFAULTLEVEL_ENUM 1U
#define KDHP_VEHCRASHHARDWARESIGNALHANDLERESPONSEBITS 0U
#define KDHP_VEHCRASHHARDWARESIGNALPOWERLIMIT_PCT 100U
#define KDHP_VEHCRASHHARDWARESIGNALSPDLIMIT 200U
#define KDHP_VEHCRASHPOWERLIMIT_PCT    0U
#define KDHP_VEHCRASHSPDLIMIT          0U
#define KDHP_WATERPUMPFLT1ALLOWRECOVERY_FLG 1
#define KDHP_WATERPUMPFLT1CLEARTIME_MS 4000U
#define KDHP_WATERPUMPFLT1CONFIRMTIME_MS 2000U
#define KDHP_WATERPUMPFLT1FAULTLEVEL_ENUM 2U
#define KDHP_WATERPUMPFLT1HANDLERESPONSEBITS 0U
#define KDHP_WATERPUMPFLT1POWERLIMIT_PCT 100U
#define KDHP_WATERPUMPFLT1SPDLIMIT     200U
#define KDHP_WATERPUMPFLT2ALLOWRECOVERY_FLG 1
#define KDHP_WATERPUMPFLT2CLEARTIME_MS 4000U
#define KDHP_WATERPUMPFLT2CONFIRMTIME_MS 2000U
#define KDHP_WATERPUMPFLT2FAULTLEVEL_ENUM 2U
#define KDHP_WATERPUMPFLT2HANDLERESPONSEBITS 0U
#define KDHP_WATERPUMPFLT2POWERLIMIT_PCT 100U
#define KDHP_WATERPUMPFLT2SPDLIMIT     200U
#define KDHP_WATERPUMPHARDWIREALLOWRECOVERY_FLG 1
#define KDHP_WATERPUMPHARDWIRECLEARTIME_MS 400U
#define KDHP_WATERPUMPHARDWIRECONFIRMTIME_MS 400U
#define KDHP_WATERPUMPHARDWIREFAULTLEVEL_ENUM 2U
#define KDHP_WATERPUMPHARDWIREHANDLERESPONSEBITS 0U
#define KDHP_WATERPUMPHARDWIREPOWERLIMIT_PCT 100U
#define KDHP_WATERPUMPHARDWIRESPDLIMIT 200U
#define KDHP_WATERPUMPPWMALLOWRECOVERY_FLG 1
#define KDHP_WATERPUMPPWMCLEARTIME_MS  20000U
#define KDHP_WATERPUMPPWMCONFIRMTIME_MS 10000U
#define KDHP_WATERPUMPPWMFAULTLEVEL_ENUM 2U
#define KDHP_WATERPUMPPWMHANDLERESPONSEBITS 0U
#define KDHP_WATERPUMPPWMPOWERLIMIT_PCT 100U
#define KDHP_WATERPUMPPWMSPDLIMIT      200U
#define KDHP_WRITETOCALAREAINVALIDALLOWRECOVERY_FLG 1
#define KDHP_WRITETOCALAREAINVALIDFAULTLEVEL_ENUM 1U
#define KDHP_WRITETOCALAREAINVALIDHANDLERESPONSEBITS 0U
#define KDHP_WRITETOCALAREAINVALIDPOWERLIMIT_PCT 100U
#define KDHP_WRITETOCALAREAINVALIDSPDLIMIT 200U
#define KDHP_XBSLOSSCANNETALLOWRECOVERY_FLG 1
#define KDHP_XBSLOSSCANNETFAULTLEVEL_ENUM 2U
#define KDHP_XBSLOSSCANNETHANDLERESPONSEBITS 256U
#define KDHP_XBSLOSSCANNETPOWERLIMIT_PCT 100U
#define KDHP_XBSLOSSCANNETSPDLIMIT     200U
#define MAXUINT16_VAL                  65535U
#define MAXUINT8_VAL                   255U
#define MCUERR15LEVEL_SP               2U
#define MCUERR26LEVEL_SP               1U
#define MCUERR40LEVEL_SP               1U
#define MCUERR8LEVEL_SP                2U
#define S11P04_MARK                    10U
#define Z18_MARK                       14U

/* Exported data declaration */
#include "derivative.h"

/* Declaration for custom storage class: CAL_10_DHP */
extern CAL_DHP boolean_T KDHP_ABS232MissingActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_ABSFaultStart_ms;
extern CAL_DHP boolean_T KDHP_ABSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ABSSpdInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ABSWorkErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ACCHWSignalAbnormalActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_ACCHWSignalAbnormal_ms;
extern CAL_DHP boolean_T KDHP_APPData12DFlashInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_APPData12EEPROMInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_APPData3DFlashInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_APPData3EEPROMInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_APPData4DFlashInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_APPData4EEPROMInvalidActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_AccPdlHDownDeathAreaValue_mv;
extern CAL_DHP uint16_T KDHP_AccPdlHLDeathAreaOffestValue_mv;
extern CAL_DHP uint16_T KDHP_AccPdlHLRatDownLimitValue_pct;
extern CAL_DHP uint16_T KDHP_AccPdlHLRatUpLimitValue_pct;
extern CAL_DHP uint16_T KDHP_AccPdlHUpDeathAreaValue_mv;
extern CAL_DHP boolean_T KDHP_AccPdlHVoltHighActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AccPdlHVoltLowActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_AccPdlLDownDeathAreaValue_mv;
extern CAL_DHP boolean_T KDHP_AccPdlLHVoltDeathActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_AccPdlLUpDeathAreaValue_mv;
extern CAL_DHP boolean_T KDHP_AccPdlLVoltHighActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AccPdlLVoltLowActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_AccPdlPowerVoltDownLimValue_mv;
extern CAL_DHP uint16_T KDHP_AccPdlPowerVoltUpLimValue_mv;
extern CAL_DHP boolean_T KDHP_AccPdlSenRefVoltHighActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AccPdlSenRefVoltLowActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AccelPdlRatActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AccelPdlRatDeathActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AllResponseBits_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllResponseBits_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceDropPwrPct_Ovrdflg;
extern CAL_DHP uint8_T KDHP_AllVehDeviceDropPwrPct_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceDropRpmPct_Ovrdflg;
extern CAL_DHP uint8_T KDHP_AllVehDeviceDropRpmPct_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidActiveDischarge_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidActiveDischarge_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCharge_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCharge_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCondition_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCondition_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCreep_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCreep_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCruise_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidCruise_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidDCDC_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidDCDC_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidFeedback_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidFeedback_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidPTC_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidPTC_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidPreCharge_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceForbidPreCharge_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceMaxFaultLever_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceMaxFaultLever_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceMcuDisEnable_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceMcuDisEnable_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceNormalPowerDown_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceNormalPowerDown_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffAllRelay_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffAllRelay_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffDeviceRelay_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffDeviceRelay_Ovrdval;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffMainRelay_Ovrdflg;
extern CAL_DHP boolean_T KDHP_AllVehDeviceOffMainRelay_Ovrdval;
extern CAL_DHP boolean_T KDHP_AppDataCheckFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AuxBattVoltHighFltActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_AuxBattVoltHighInstFltValue_dV;
extern CAL_DHP uint8_T KDHP_AuxBattVoltHighInstWarmValue_dV;
extern CAL_DHP boolean_T KDHP_AuxBattVoltHighWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_AuxBattVoltLowFltActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_AuxBattVoltLowInstFltValue_dV;
extern CAL_DHP uint8_T KDHP_AuxBattVoltLowInstWarmValue_dV;
extern CAL_DHP boolean_T KDHP_AuxBattVoltLowWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMS113MissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMS303MissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSBattOverTActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_BMSBatt_OverTErrValue;
extern CAL_DHP boolean_T KDHP_BMSCellOverUActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSCellUnderUActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_BMSCell_OverUErrValue;
extern CAL_DHP uint16_T KDHP_BMSCell_UnderUErrValue;
extern CAL_DHP boolean_T KDHP_BMSDischrgPwrAbnormalActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSFlt2ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSFlt3ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSFlt4ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSFltUnmatchActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSMissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSModeErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSOverUActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BMSUnderUActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_BMS_OverUErrValue;
extern CAL_DHP uint16_T KDHP_BMS_UnderUErrValue;
extern CAL_DHP boolean_T KDHP_BattEnergyTooLowActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BrkDSCheck0ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_BrkDSCheck1ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_CalDataCheckFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgFaultActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgLockCheckTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgModeAbnormalActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgModeInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgOBCSleepTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgStopAbnormalActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgStopLockErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgStopModeInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ChrgStopOperTimeoutActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_ChrgendMCUmissing_ms;
extern CAL_DHP uint16_T KDHP_CollisionKeepTime_ms;
extern CAL_DHP uint8_T KDHP_CoolErrMotTempUpRate_pct;
extern CAL_DHP uint8_T KDHP_CoolErrMotTemp_C;
extern CAL_DHP boolean_T KDHP_CoolSysErrActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_CoolSysErr_MCUElecMotT;
extern CAL_DHP uint8_T KDHP_CoolSysErr_MCUIGBTT;
extern CAL_DHP uint8_T KDHP_CoolSysErr_MCUT;
extern CAL_DHP boolean_T KDHP_CruiseKeyJamFltActionSwitchOpen_flg;
extern CAL_DHP uint32_T KDHP_CruiseKeyJam_ms;
extern CAL_DHP boolean_T KDHP_CruiseKeyOpenFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_CruiseKeyShortedFltActionSwitchOpen_flg;
extern CAL_DHP int16_T KDHP_DCChrgPortNormalT_C;
extern CAL_DHP int16_T KDHP_DCChrgPortOverT1_C;
extern CAL_DHP int16_T KDHP_DCChrgPortOverT2_C;
extern CAL_DHP boolean_T KDHP_DCChrgPortOverTActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DCDCLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DCDCMissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DCDCModeErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DCDCStopWorkTimeoutActionSwitchOpen_flg;
extern CAL_DHP uint32_T KDHP_DCPortTFault_ms;
extern CAL_DHP boolean_T KDHP_DIDDataDFlashInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DIDDataEEPROMInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DcdcFlt2ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_DidDataCheckFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EACLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EBDWorkErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ECCLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EHULossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EPBWorkErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EPSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EPSWorkErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ESPWorkErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclAuthenticFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclChipHWFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclEEPROMFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclLinCommFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclLockGndFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclLockTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclMasterIReqInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclMasterReqTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclMotorDriverFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclMotorNoActActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclMotorOverloadActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclPwrSupplyFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclSensorHWFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclSensorStsFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_EsclUnlockTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_GWLossCanNetActionSwitchOpen_flg;
extern CAL_DHP real32_T KDHP_GearDRegenTq_Nm;
extern CAL_DHP real32_T KDHP_GearRRegenTq_Nm;
extern CAL_DHP boolean_T KDHP_GearSingleNotInAeraActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_GradsSpeed1;
extern CAL_DHP uint16_T KDHP_GradsSpeed2;
extern CAL_DHP uint16_T KDHP_GradsSpeed_basisTime;
extern CAL_DHP boolean_T KDHP_HS1FaultOpenLoad_Valid;
extern CAL_DHP boolean_T KDHP_HVActiveTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_HVDCDCActiveTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_HVDownTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_HVILErrActionSwitchOpen_flg;
extern CAL_DHP uint32_T KDHP_HVILPulseTime_Lower_us;
extern CAL_DHP uint32_T KDHP_HVILPulseTime_Upper_us;
extern CAL_DHP uint8_T KDHP_HVIL_FreHZ;
extern CAL_DHP uint8_T KDHP_HVIL_FreOffset;
extern CAL_DHP uint16_T KDHP_HVIL_HVReady_ConfirmTime;
extern CAL_DHP uint8_T KDHP_HVIL_VehicleSpeed;
extern CAL_DHP boolean_T KDHP_HVPwrUpTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_HVUpTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_HistDataCheckFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ICMLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ICMVehSpdChkInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_IChrgErrorActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_IGN1FeedVoltFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_IGN2FeedVoltFltActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_KGearDrange_Single;
extern CAL_DHP uint8_T KDHP_KGearNeutral_Single;
extern CAL_DHP uint8_T KDHP_KGearReverse_Single;
extern CAL_DHP boolean_T KDHP_LVUpBMSPwrUpAllwTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_LVUpBMSTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_LVUpDCDCTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_LVUpMCUTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUCANBusOffActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUCANComActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUChipPowerFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUCoverFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUCoverWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDCUOverUHWFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDCUShoCircActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcCrrtOverRedundActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUOverUFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUOverURedundActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUOverUWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUSnsrRatiActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUUnderUFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDcUUnderUWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDischargeTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUDischrgActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotOverCrrtActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotOverSpdFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotOverSpdWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotOverTFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotOverTWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotReslvActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotStopTurnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotTSnsrRatiActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUElecMotUnderTActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_MCUErrNum3Value_V1;
extern CAL_DHP uint16_T KDHP_MCUErrNum3Value_V2;
extern CAL_DHP boolean_T KDHP_MCUExitTorqTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUFlt1ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUFlt2ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUFlt3ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUFltUnmatchActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUHVActiveTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUHWSamplingFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUHwCurrOverActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUHwCurrOverRedundActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUIGBTHWActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUIGBTOverTFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUIGBTOverTWarnActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUIGBTUnderTActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUIGBTphaseTCheckErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCULossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCULowBattUnderUActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUMissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUModeErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUMotTUpRateActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUOverTActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUPhaACCrrtSnsrRatiActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUPhaseLossActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUPwrModRedundActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUSpdInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUTSnsrRatiActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUTorqCheckErrActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUTorqOuterRangeActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUTrqInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_MCUVersionMismatchActionSwitchOpen_flg;
extern CAL_DHP int16_T KDHP_MCU_DcCrrtErrValue_A;
extern CAL_DHP uint16_T KDHP_MCU_DcUErrValue_V;
extern CAL_DHP boolean_T KDHP_NMLipHomeActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_OBCLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_OBCMissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_OBCWakeupTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ObcFlt2ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ObcFlt3ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_OverDiagnVoltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_PEPSFailedActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_PTBusOffActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_PTCanLossActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_PerformancePwr_Kw;
extern CAL_DHP uint8_T KDHP_PwrLimit1_basisSpd;
extern CAL_DHP uint8_T KDHP_PwrLimit1_basisTime;
extern CAL_DHP uint8_T KDHP_PwrLimit2_basisSpd;
extern CAL_DHP uint8_T KDHP_PwrLimit2_basisTime;
extern CAL_DHP boolean_T KDHP_RegenAbnormalActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_RegenAbnormal_ms;
extern CAL_DHP boolean_T KDHP_SCRActualSpeedLowActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_SCRTargetSpdUnfollowedActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_SGearDRelease_Single;
extern CAL_DHP uint8_T KDHP_SGearDrange_Single;
extern CAL_DHP uint8_T KDHP_SGearNeutral_Single;
extern CAL_DHP uint8_T KDHP_SGearRRelease_Single;
extern CAL_DHP uint8_T KDHP_SGearReverse_Single;
extern CAL_DHP boolean_T KDHP_SRSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_SRSMissingActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_SSBSyncFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_ShiftKnobCheckTimeoutActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_SpeedInvalidActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_SpeedLimitThreshold_Grads;
extern CAL_DHP uint8_T KDHP_SpeedLimit_P10292F;
extern CAL_DHP boolean_T KDHP_TBOXLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_TMSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_TMSReqInvalidActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_TestCrashPWM_HZ;
extern CAL_DHP uint16_T KDHP_TestHVILPWM_HZ;
extern CAL_DHP uint8_T KDHP_TestPWMHZ_offset;
extern CAL_DHP uint16_T KDHP_TestVacpumpPWM_HZ;
extern CAL_DHP uint16_T KDHP_TestWaterpumpPWM_HZ;
extern CAL_DHP boolean_T KDHP_UnderDiagnVoltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VACHzFlt1ActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VACHzFlt2ActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_VCUCanNetLineOffTime_ms;
extern CAL_DHP boolean_T KDHP_VCUChrgReqLimFacActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwCanNetLineOffActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwHS1FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS1FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS2FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS3FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS4FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS5FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS6FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS7FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLS8FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLSEsclPwrFltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLSIGN1FltActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VCUHwLSIGN2FltActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_VacHzFlt1;
extern CAL_DHP uint8_T KDHP_VacHzFlt1Offset;
extern CAL_DHP uint16_T KDHP_VacHzFlt2;
extern CAL_DHP uint8_T KDHP_VacHzFlt2Offset;
extern CAL_DHP boolean_T KDHP_VacPumpHardwireActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VcuControlDeviceInstErrValid;
extern CAL_DHP boolean_T KDHP_VehCrashActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VehCrashHardwareCanSignalActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_VehCrashHardwareSignalActionSwitchOpen_flg;
extern CAL_DHP real32_T KDHP_VehSpd_Accuracy;
extern CAL_DHP uint16_T KDHP_WaitMoreForFltSecond_ms;
extern CAL_DHP uint16_T KDHP_WaitTime1_GradsbasisTime_ms;
extern CAL_DHP uint16_T KDHP_WaitTime2_GradsbasisTime_ms;
extern CAL_DHP boolean_T KDHP_WaterPumpFlt1ActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_WaterPumpFlt1_PCTOffset;
extern CAL_DHP boolean_T KDHP_WaterPumpFlt2ActionSwitchOpen_flg;
extern CAL_DHP uint8_T KDHP_WaterPumpFlt2_PCTOffset;
extern CAL_DHP boolean_T KDHP_WaterPumpHardwireActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_WaterPumpPWMActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_WriteToCalAreaInvalidActionSwitchOpen_flg;
extern CAL_DHP boolean_T KDHP_XBSLossCanNetActionSwitchOpen_flg;
extern CAL_DHP uint16_T KDHP_preResponseBits_Grads;

#endif                                 /* RTW_HEADER_DHP_Cal_Data_h_ */

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
